In [2]:
pip install ipykernel

In [3]:
import numpy as np

In [4]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr1=np.array([[1,2,3],[4,5,6]])

In [6]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr1.shape

(2, 3)

In [9]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(1,10,2).shape

(5,)

In [14]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [15]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [16]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [17]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [18]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [28]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(2,3)

array([[0.52168277, 0.7405519 , 0.76524913],
       [0.66455674, 0.01303398, 0.95007805]])

In [30]:
print(np.random.randn(5,3))

[[-0.6122033   1.79903237  0.7987522 ]
 [ 0.54296335  0.27348767  0.7354701 ]
 [-0.94342644 -0.0660718  -2.45690977]
 [ 0.30072027  1.02630533 -0.02536056]
 [ 0.88098743  0.99980403 -0.40000552]]


In [32]:
np.random.randint(1,100)

73

In [34]:
np.random.randint(1,100,20)

array([42, 89, 11, 79, 30, 15, 32, 62, 59, 14, 99, 74, 31, 57, 60, 50, 41,
       43, 98, 50])

In [35]:
np.random.randint(1,100,(4,4))

array([[89, 50, 58, 55],
       [42, 42,  6, 43],
       [99, 83, 62, 72],
       [98, 62, 21, 92]])

In [38]:
arr = np.arange(0,11)

In [37]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [40]:
arr[-1:7:-1]

array([10,  9,  8])

In [41]:
arr[2:7:3]

array([2, 5])

In [42]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])